<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zoo.common\Zoo.common.csproj" />
    <ProjectReference Include="..\Zoo.model\Zoo.model.csproj" />
    <ProjectReference Include="..\Zoo.repository\Zoo.repository.csproj" />
  </ItemGroup>

</Project>
